### ISSUE TITLE
Check and get rid of the BOM header of SQL files

### ISSUE THREAD

**Issue by tmoriki** [oneops/db-schema#17]
Hi maintainers,

I submitted a pull request to get rid of the BOM header on SQL files. Thanks for accept this.
But the new commit reverts the file into wrong state. (#61cd5868ebdfb2896b7cbd40627812eb2e8ae50c)
Can you fix this?

BOM: byte order mark is HARMFUL under the postgres 8.x environments.
This change affects all people using oneops/setup with Vagrant boxes (CentOS-6.7 and -7.x).

You can see the BOM header by using this command.
$ vi -b db/kloopzcm-postprocess.sql

Thanks.

**Comment by vitaliyzinchenko** [comment]
Sorry, my bad, git merged it improperly into my local branch. Fixed
